// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBohz9Z14y4alUpvmVJ66YMdvlPeXxJsGQ',
    appId: '1:339853353480:web:9217969ef2c2a66f59a7bd',
    messagingSenderId: '339853353480',
    projectId: 'flutter-fb1e2',
    authDomain: 'flutter-fb1e2.firebaseapp.com',
    storageBucket: 'flutter-fb1e2.firebasestorage.app',
    measurementId: 'G-XLCM5H17RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX4OYT4H-dBXQ2vq2q5bBxNfhxkD1q9X0',
    appId: '1:339853353480:android:0a87db1543f204b959a7bd',
    messagingSenderId: '339853353480',
    projectId: 'flutter-fb1e2',
    storageBucket: 'flutter-fb1e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyNtacZWl9VtZv5z-iuNGACXDvLKNqLx0',
    appId: '1:339853353480:ios:30fe90d32309f71c59a7bd',
    messagingSenderId: '339853353480',
    projectId: 'flutter-fb1e2',
    storageBucket: 'flutter-fb1e2.firebasestorage.app',
    iosBundleId: 'com.example.tests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyNtacZWl9VtZv5z-iuNGACXDvLKNqLx0',
    appId: '1:339853353480:ios:30fe90d32309f71c59a7bd',
    messagingSenderId: '339853353480',
    projectId: 'flutter-fb1e2',
    storageBucket: 'flutter-fb1e2.firebasestorage.app',
    iosBundleId: 'com.example.tests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBohz9Z14y4alUpvmVJ66YMdvlPeXxJsGQ',
    appId: '1:339853353480:web:d47957d4816ec13059a7bd',
    messagingSenderId: '339853353480',
    projectId: 'flutter-fb1e2',
    authDomain: 'flutter-fb1e2.firebaseapp.com',
    storageBucket: 'flutter-fb1e2.firebasestorage.app',
    measurementId: 'G-XPLVF6XEB7',
  );
}
